services:
  # --- ETL Infrastructure ---
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.3'
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck: 
      test: ["CMD", "sh", "-c", "nc -z localhost 2181 || exit 1"] # Check if port 2181 is open
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Give Zookeeper some time to start up initially
    networks:
      - book-recommend-network  # 接入公共网络

  kafka:
    image: confluentinc/cp-kafka:7.5.3 
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094" # For external access if needed
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # --- ADD THESE LINES TO INCREASE MESSAGE SIZE LIMIT ---
      KAFKA_MESSAGE_MAX_BYTES: 1572864000 # Set to 1.5GB (1.5 * 1024 * 1024 * 1024)
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1572864000 # Should be >= KAFKA_MESSAGE_MAX_BYTES
      KAFKA_MAX_REQUEST_SIZE: 1572864000 # Should be >= KAFKA_MESSAGE_MAX_BYTES
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck: 
      test: ["CMD", "sh", "-c", "kafka-topics --bootstrap-server kafka:29092 --list > /dev/null || exit 1"] 
      interval: 10s
      timeout: 10s 
      retries: 5
      start_period: 30s 
    networks:
      - book-recommend-network  # 接入公共网络

  kafka_connect:
    image: confluentinc/cp-kafka-connect:8.0.0
    container_name: kafka_connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_GROUP_ID: connect-cluster-group
      CONNECT_LISTENERS: http://0.0.0.0:8083
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka_connect
      
      # --- 内部主题配置 ---
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_CONFIG_STORAGE_PARTITIONS: 1
      CONNECT_OFFSET_STORAGE_PARTITIONS: 25
      CONNECT_STATUS_STORAGE_PARTITIONS: 5

      CONNECT_CONFIG_STORAGE_CLEANUP_POLICY: "compact"
      CONNECT_OFFSET_STORAGE_CLEANUP_POLICY: "compact"
      CONNECT_STATUS_STORAGE_CLEANUP_POLICY: "compact"

      CONNECT_HEAP_OPTS: "-Xmx2G -Xms2G"
      CONNECT_LINGER_MS: 50
      CONNECT_BATCH_SIZE: 8192
      CONNECT_MAX_REQUEST_SIZE: 1048576
      CONNECT_MAX_PARTITION_FETCH_BYTES: 1048576

      # 内部转换器也需要设置，以确保 Connect 内部通信正常
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "true"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"

      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      # 必须包含我们挂载的 clickhouse 目录
      CONNECT_PLUGIN_PATH: "/usr/share/confluent-hub-components,/usr/share/java"

      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO

    command:
      - bash
      - -c
      - |
        echo "Waiting for Kafka to be ready..."
        cub kafka-ready -b kafka:29092 1 20

        echo "Installing Debezium connectors..."
        confluent-hub install --no-prompt debezium/debezium-connector-mysql:3.1.2
        confluent-hub install --no-prompt debezium/debezium-connector-mongodb:3.1.2

        echo "Starting Kafka Connect..."
        /etc/confluent/docker/run

    volumes:
      # 挂载你下载的 clickhouse connector 目录（Windows 路径）
      - "E:/0CQU_Learning_Materials/大四上/0 大数据生产实习/Book-Recommendation-System/backend/clickhouse-clickhouse-kafka-connect-v1.3.1:/usr/share/java/clickhouse-kafka-connect"

    depends_on:
      kafka:
        condition: service_healthy
      auth_db:
        condition: service_healthy
      book_db_mongo:
        condition: service_healthy
      mongo_setup:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy

    networks:
      - book-recommend-network


networks:
  book-recommend-network:
    external: true 

volumes:
  zookeeper_data:
  kafka_data: