services:
  mysql_db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: book_app_db
      MYSQL_USER: cqu123
      MYSQL_PASSWORD: 123456
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql_db
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data: